services:
  api:
    image: ghcr.io/luvnationdev/ln-foot-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_API_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KC_ISSUER_URI=${KC_ISSUER_URI}
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  drizzle-studio:
    image: ghcr.io/marcjazz/drizzle-studio:latest
    container_name: drizzle-studio
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres

  keycloak:
    image: ghcr.io/marcjazz/keycloak-auth-theme:latest
    env_file:
      - .docker/keycloak/keycloak.env
    ports:
      - '8081:8080'
    command:
      - 'start-dev'
      - '--import-realm'
      - '--spi-theme-static-max-age=-1'
      - '--spi-theme-cache-themes=false'
      - '--spi-theme-cache-templates=false'
    restart: unless-stopped
    volumes:
      - ./.docker/keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    entrypoint: ['/usr/local/bin/docker-entrypoint.sh']
    command: server /data --console-address ":9001"
    ports:
      - '9000-9001:9000-9001'
    env_file:
      - .docker/minio/.env
    environment:
      - APP_CLIENT_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - APP_CLIENT_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
      - ./.docker/minio/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./.docker/minio/app-client-policy.json:/app_client_policy.json
      

volumes:
  pgdata:
  minio-data:
