services:
  api:
    image: ghcr.io/Hublot-Tech/ln_foot_api:latest
    ports:
      - "8081:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_API_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KC_ISSUER_URI=${KC_ISSUER_URI}
    depends_on:
      - postgres
    networks:
      - lnfoot

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lnfoot

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - lnfoot


  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      - KC_LOG_LEVEL=INFO
      - KC_REALM_NAME=${KC_REALM_NAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - lnfoot
    command:
      - "start-dev"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - ./keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - lnfoot

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/:/etc/prometheus/
    ports:
      - 9090:9090
    networks:
      - lnfoot

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - lnfoot

volumes:
  pgdata:
  minio-data:
  grafana-storage:
  portainer_data:

networks:
  lnfoot:
