services:
  api:
    image: ghcr.io/hublot-tech/ln-foot-api:latest
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_API_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - KC_ISSUER_URI=${KC_ISSUER_URI}
    depends_on:
      - postgres
    networks:
      - lnfoot

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lnfoot

  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - lnfoot


  keycloak:
    image: ghcr.io/marcjazz/keycloak-auth-theme:latest
    env_file:
      - keycloak/keycloak.env
    networks:
      - lnfoot
    command:
      - "start"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    restart: unless-stopped
    volumes:
      - ./keycloak/config/:/opt/keycloak/data/import/:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - lnfoot

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/:/etc/prometheus/
    networks:
      - lnfoot

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - lnfoot
  
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "9443:9443"
      - "9000-9001:9000-9001"
      - "3000:3000"
      - "9090:9090"
    networks:
      - lnfoot

volumes:
  pgdata:
  minio-data:
  grafana-storage:
  portainer_data:

networks:
  lnfoot:
    driver: bridge