%YAML 1.1
---
name: NestJS Assistant
version: 0.1.0
schema: v1

api_key: &api_key sk-84cc37a9fa084b12ae415ea9549c3cb8

edit_templates: &edit_templates
  edit: |
    You are a code editing assistant. You will receive code and instructions on how to modify it. Your output should consist ONLY of the complete, modified code block, without any surrounding text, explanations, or comments. Prioritize syntactically correct and semantically relevant code that follows best practices for the specified programming language.

    Original code:
    \`\`\`{{{language}}}
    {{{codeToEdit}}}
    \`\`\`

    Instructions: {{{userInput}}}

    Modified code:
    \`\`\`{{{language}}}

model_defaults: &model_defaults
  provider: openai
  apiBase: https://ai.kivoyo.com/api
  apiKey: *api_key
  env:
    useLegacyCompletionsEndpoint: false
  cacheBehavior:
    cacheSystemMessage: true
    cacheConversation: true
  promptTemplates:
    <<: *edit_templates
  chatOptions:
    baseSystemMessage: >-
      You are a senior expert software developer who gives helpful, concise, and accurate responses.  You prioritize providing syntactically correct code blocks. When you provide code, always include the language and file name in the info string (e.g., '```python path/to/the/file.ext').  If you are unsure about a user's request, ask clarifying questions *before* attempting to provide a response.  Focus on delivering complete and accurate information.

mcpServers:
  - name: sequential-thinking
    command: docker
    args:
      - "run"
      - "--rm"
      - "-i"
      - "mcp/sequentialthinking"
  - name: fetch
    command: docker
    args:
      - "run"
      - "--rm"
      - "-i"
      - "mcp/fetch"
  - name: Brave
    command: docker
    args:
      - "run"
      - "--rm"
      - "-i"
      - "-e"
      - "BRAVE_API_KEY"
      - "mcp/brave-search"
    env:
      BRAVE_API_KEY: "BSAKr3av5aHe1m_ZIwqQA7vbxe-kWXA"
  - name: Dev Server
    command: yarn
    args:
      - "start:dev"
    env:
      PORT: "3001"
  - name: Testing truc
    command: bash
    args:
      - |
        sleep infinity
    env:
      PORT: "3001"
  - name: Memory
    command: docker
    args:
      - "run"
      - "-i"
      - "--rm"
      - "mcp/memory"
  - name: local-filesystem
    command: "docker"
    args:
      - "run"
      - "-i"
      - "--rm"
      - "--mount"
      - "type=bind,src=/home/marco/Projects/playground/ln-foot-api/,dst=/projects"
      - "mcp/filesystem"
      - "/projects"

models:
  - <<: *model_defaults
    name: Qwen2.5 Coder 14b
    model: qwen2.5-coder-14b-instruct # tools
    roles:
      - chat # Continue.dev's recommandation
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 128000

  - <<: *model_defaults
    name: Llama3.1 8b Instruct
    model: llama3.1-8b-instruct # tools
    roles:
      - chat # Continue.dev's recommandation
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 128000

  - <<: *model_defaults
    name: Llama3.1 8b Autocomplete
    model: llama3.1-8b # tools
    roles:
      - autocomplete
    defaultCompletionOptions:
      contextLength: 128000
    chatOptions:
      baseSystemMessage: |
        You are a specialized AI assistant designed EXCLUSIVELY for code auto-completion. Your ONLY function is to predict and generate the most likely and correct code snippet to fill in the gap between a given prefix and suffix of code. You must adhere to these STRICT rules:
        - OUTPUT CODE ONLY: Your output MUST consist ONLY of the code snippet that completes the code. Do NOT include ANY other text, explanations, comments, conversation, or any other non-code content. You must provide solely code.
        - SYNTAX AND SEMANTICS: The generated code MUST be syntactically correct and semantically relevant to the surrounding code.
        - IDIOMATIC CODE: Favor idiomatic code that follows established conventions and best practices for the programming language.
        - CONTEXT AWARE: Your completion MUST consider the prefix, suffix, the filename, the repository name, and the overall codebase structure.
        - CONCISE COMPLETION: Prioritize short and likely completions over longer or more speculative ones.
        - NO CONVERSATION: DO NOT engage in any conversation. Do NOT ask questions. Do NOT provide explanations. You are a code-generating machine, not a conversational assistant.
        - FAIL SILENTLY: If you are unable to generate a reasonable completion, provide an empty string ("") as your output.

        Your ENTIRE output should consist ONLY of the generated code or an empty string.

  - <<: *model_defaults
    name: Llama3.1 8b Apply
    model: llama3.1-8b
    roles:
      - apply
      - edit
    defaultCompletionOptions:
      contextLength: 128000
    chatOptions:
      baseSystemMessage: |
        You are a code assistant that does two things - you either edit a code snippet as provided, or generate the changes that needs to occur in a code snippet. Your key rule is to provide code that fits seamlessly with the surrounding context, follows best practices for the programming language, and minimizes disruption to existing functionality.

  - <<: *model_defaults
    name: Llama3.1 8b Summarizer
    model: llama3.1-8b
    roles:
      - summarize
    defaultCompletionOptions:
      contextLength: 128000
      temperature: 0.7
      maxTokens: 2000

  - <<: *model_defaults
    name: Gemma3 12b
    model: gemma3-12b # vision
    roles:
      - chat
      - edit
    defaultCompletionOptions:
      contextLength: 128000
      temperature: 0.7
    capabilities:
      - image_input

  - <<: *model_defaults
    name: Text embedding 3-small
    model: text-embedding-3-small
    roles:
      - embed

context:
  - uses: continuedev/diff-context
  - uses: continuedev/codebase-context
  - uses: continuedev/url-context
  - uses: continuedev/folder-context
  - uses: continuedev/terminal-context
  - uses: continuedev/code-context
  - uses: continuedev/file-context
  - uses: continuedev/problems-context
  - provider: docs
docs:
  - uses: yoannravel/nestjs-docs

prompts:
  - name: API route
    description: Create an API route.
    prompt: Create an API route with the following functionality.