spring:
  application:
    name: ln-foot 
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lnfootdb}?search_path=lnfoot_api
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    schema: lnfoot_api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://127.0.0.1:8180/realms/ln-foot-01}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  url: ${SERVER_URL:http://localhost:8080}

minio:
  url: ${MINIO_API_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:access-key}
  secret-key: ${MINIO_SECRET_KEY:secret-key}
  bucket: uploads

logging:
  level:
    root: DEBUG
    com.hublots.ln_foot: DEBUG

springdoc:
  paths-to-match: /api/**

notchpay:
  api: 
    key: ${NOTCHPAY_API_KEY:notchpay_api_key}
    base-url: ${NOTCHPAY_API_BASE_URL:https://api.notchpay.co}