spring:
  application:
    name: ln-foot
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lnfootdb}?search_path=lnfoot_api
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    schema: lnfoot_api
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://127.0.0.1:8180/realms/ln-foot-01}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: ${MINIO_API_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:np75ZHQcKOtDL5Gn4xo3}
  secret-key: ${MINIO_SECRET_KEY:VJKg6XJTjW6Z7TUTs5pIM6LzOZpIfrb784Ncjx2b}
  bucket: uploads

logging:
  level:
    root: DEBUG
    com.hublots.ln_foot: DEBUG
