spring:
  application:
    name: ln-foot 
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lnfootdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:O26bQI32vYJlqDNp634lP8ZQ}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          create_namespaces: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8081/realms/ln-foot-01}

server:
  port: 8080
  url: ${SERVER_URL:http://localhost:8080}

minio:
  url: ${MINIO_API_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:lnfoot-admin}
  secret-key: ${MINIO_SECRET_KEY:Eb8QEo8VWCdBSqsc}

logging:
  level:
    root: DEBUG
    com.hublots.ln_foot: DEBUG

springdoc:
  paths-to-match: /api/**

notchpay:
  api-key: ${NOTCHPAY_API_KEY:notchpay_api_key}
  api-base-url: ${NOTCHPAY_API_BASE_URL:https://api.notchpay.co}
  webhook-secret: ${NOTCHPAY_WEBHOOK_SECRET:notchpay_webhook_secret}

external:
  api:
    sportsUrl: ${EXTERNAL_SPORTS_API_URL:https://api-football-v1.p.rapidapi.com/v3}
    sportsKey: ${EXTERNAL_SPORTS_API_KEY:07047667damsh70009995f0bb861p17853ejsn5e9465d1ecb2}
    rapidApiHost: api-football-v1.p.rapidapi.com
    sourceName: RapidAPIFootballV1

application:
  sync:
    dailyCron: ${APPLICATION_SYNC_DAILY_CRON:0 5 0 * * ?} # Default daily at 00:05 UTC
    hourlyCron: ${APPLICATION_SYNC_HOURLY_CRON:0 0 */1 * * ?} # Default hourly
    interestedLeagues:
      # Cameroon
      - { name: 'Elite One', country: 'Cameroon' }
      - { name: 'Elite Two', country: 'Cameroon' }
      # France
      - { name: 'Ligue 1', country: 'France' }
      - { name: 'Ligue 2', country: 'France' }
      - { name: 'Feminine Division 1', country: 'France' } # Première ligue Arkema
      # England
      - { name: 'Premier League', country: 'England' }
      - { name: 'Championship', country: 'England' }
      - { name: 'League One', country: 'England' }
      # Spain
      - { name: 'La Liga', country: 'Spain' }
      - { name: 'Segunda División', country: 'Spain' }
      - { name: 'Primera RFEF', country: 'Spain' } # Liga 3
      # Italy
      - { name: 'Serie A', country: 'Italy' }
      - { name: 'Serie B', country: 'Italy' }
      - { name: 'Serie C', country: 'Italy' }
      # Germany
      - { name: 'Bundesliga', country: 'Germany' }
      - { name: '2. Bundesliga', country: 'Germany' }
      # Latvia
      - { name: 'Virsliga', country: 'Latvia' }
      # Romania
      - { name: 'Liga I', country: 'Romania' }
      # USA
      - { name: 'Major League Soccer', country: 'USA' }
      - { name: 'MLS Next Pro', country: 'USA' }
      # China
      - { name: 'Super League', country: 'China' }
      # Saudi Arabia
      - { name: 'Saudi Professional League', country: 'Saudi Arabia' }
      # Tanzania
      - { name: 'NBC Premier League', country: 'Tanzania' }