name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}:latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Jar
        run: ./gradlew clean build

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: downcase REPO
        run: |
          echo "GHCR_IMAGE=${GHCR_IMAGE,,}" >>${GITHUB_ENV}

      - name: Build and Push Docker Image
        run: |
          docker build -t $GHCR_IMAGE .
          docker push $GHCR_IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    env:
      WORKDIR: /opt/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]') 

    permissions:
      contents: read

    steps:
      - name: downcase REPO
        run: |
          echo "WORKDIR=/opt/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}

      - name: Copy compose, keycloak theme, and monitoring files to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: compose.yml,keycloak,monitoring
          target: ${{ env.WORKDIR }}
          strip_components: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p ${{ env.WORKDIR }} && cd ${{ env.WORKDIR }}

            echo "${{ secrets.ENV_FILE }}" > .env

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
