name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      GHCR_IMAGE: ghcr.io/${{ github.repository }}:latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Jar
        run: ./gradlew clean build

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: downcase REPO
        run: |
          echo "GHCR_IMAGE=${GHCR_IMAGE,,}" >>${GITHUB_ENV}

      - name: Build and Push Docker Image
        run: |
          docker build -t $GHCR_IMAGE .
          docker push $GHCR_IMAGE
